### ISSUE TITLE
Issue downloading Sentinel-1 data over Gabon

### ISSUE THREAD

**Issue by purnelldj** [gbelouze/geefetch#21]
Not finding any Sentinel-1 data over Gabon. Sentinel-2 data is downloading no problem. Using this config file as an input (with purposefully enlarged AOI and date range):
```yaml
data_dir: ~/data/lope-sample
satellite_default:
  resolution: 10
  tile_size: 1_000  # note tile_size = tile_size * resolution
  dtype: UInt16
  composite_method: MEDIAN
  aoi:
    spatial:
      left: 330_000
      right: 480_000
      bottom: 350_000
      top: 500_000
      epsg: 5223
    temporal:
      start_date: 2017-01-01
      end_date: 2025-12-31
    country: Gabon
  gee:
    ee_project_id: geefetch
    max_tile_size: 5 # in MB
s1:
  composite_method: MEAN
s2: {}
gedi: 
  format: GEOJSON
```
not finding any Sentinel-1 data to download. Have independently checked and Sentinel-1 data exists during this time period at this location.
Error messages look like:
```bash
Found 0 Sentinel-1 image.Check region BoundingBox(left=10.651831016503765, bottom=-1.1758636674218317, right=10.741732823692287, top=-1.0853738708499236, crs=CRS.from_epsg(4326)).
```
