### ISSUE TITLE
Improving the API and UX

### ISSUE THREAD

**Issue by gbelouze** [gbelouze/geefetch#44]
Right now it's not convenient to use `geefetch` with unsupported data, or with supported data but different filtering/processing scheme. This is by design but it would also make sense to let the user plug into the `geefetch` large scale download capabilities with their own custom data.

Discussion with @purnelldj 
We can 

```python

def download_ee_image(
    image: ee.Image,
    aoi: BoundingBox,
    temporal_range: tuple[str, str],
    dtype: DType,
   -> None:
    ...
```

Or we can

```yaml
default_satellite:
   ...
tandemX:
    link: NASA/TANDEMX
```
